### ISSUE TITLE
UML Diagram Link Issue

### ISSUE THREAD

**Issue by bilalyarmaci** [emirhanbaran0/ADVANTURE_GAME_ON_CONSOL_WITH_JAVA#1]
.

**Comment by emirhanbaran0** [comment]
I solve the problem thanks for your feedback.

**Comment by emirhanbaran0** [comment]
Hi Bilal,
Sorry for late answer, can you send the project link that ı can solve the
problem about it .


Bilal Yarmacı ***@***.***>, 5 Tem 2022 Sal, 23:07 tarihinde
şunu yazdı:
